package com.guessus.app;
import android.app.*; import android.os.*; import android.graphics.Color; import android.view.*; import android.widget.*; import java.util.*;
public class MainActivity extends Activity {
 LinearLayout content; boolean dark=false; int q=0,score=0;
 String[] qs={"من أكثر واحد يضحك في وقت غلط؟","لو ربحت مليون، شنو أول حاجة تعملها؟","من أكثر واحد يتأخر على المواعيد؟","لو تسافر غدوة، وين تمشي؟","شنو أسوأ عادة عندك؟","من أكثر واحد يفهمك من نظرة؟"};
 public void onCreate(Bundle b){super.onCreate(b);home();}
 TextView t(String s,int z){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setPadding(24,18,24,18);return x;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 void base(){content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(20,25,20,20);content.setBackgroundColor(dark?Color.rgb(25,25,30):Color.WHITE);ScrollView s=new ScrollView(this);s.addView(content);setContentView(s);}
 void home(){base();TextView h=t("GuessUs 🎮",32);h.setGravity(17);content.addView(h);content.addView(t("أسئلة • توقعات • أصدقاء",18));Button p=b("▶ Play"),c=b("🏠 Create Room"),j=b("🔑 Join Room"),st=b("⚙ Settings");content.addView(p);content.addView(c);content.addView(j);content.addView(st);p.setOnClickListener(v->game());c.setOnClickListener(v->room(true));j.setOnClickListener(v->room(false));st.setOnClickListener(v->settings());}
 void room(boolean host){base();content.addView(t(host?"Create Room":"Join Room",28));if(host){TextView code=t("كود الغرفة\n"+(1000+new Random().nextInt(9000)),30);code.setGravity(17);content.addView(code);}else{EditText e=new EditText(this);e.setHint("أدخل كود الغرفة");content.addView(e);}content.addView(t("Players • 1/6",18));Button r=b("✓ Ready"),s=b("🚀 Start Game"),ch=b("💬 Chat"),back=b("← Back");content.addView(r);if(host)content.addView(s);content.addView(ch);content.addView(back);r.setOnClickListener(v->Toast.makeText(this,"Ready!",0).show());s.setOnClickListener(v->game());ch.setOnClickListener(v->chat());back.setOnClickListener(v->home());}
 void game(){base();TextView tm=t("⏱ 20",20);tm.setGravity(17);content.addView(tm);TextView qu=t(qs[q%qs.length],25);qu.setGravity(17);content.addView(qu);RadioGroup rg=new RadioGroup(this);for(String o:new String[]{"A","B","C","D"}){RadioButton r=new RadioButton(this);r.setText(o);r.setTextSize(18);rg.addView(r);}content.addView(rg);Button p=b("🎯 Predict"),skip=b("⏭ Skip"),ch=b("💬 Chat");content.addView(p);content.addView(skip);content.addView(ch);final int[] left={20};Handler h=new Handler();Runnable run=new Runnable(){public void run(){tm.setText("⏱ "+left[0]);if(left[0]-->0)h.postDelayed(this,1000);else results();}};h.post(run);p.setOnClickListener(v->{if(rg.getCheckedRadioButtonId()==-1)Toast.makeText(this,"اختار إجابة",0).show();else results();});skip.setOnClickListener(v->{q++;game();});ch.setOnClickListener(v->chat());}
 void results(){score+=3;base();content.addView(t("✨ Results",30));content.addView(t("الإجابة: A\nتوقعك: A\n\n+3 نقاط 🎉",21));content.addView(t("🏆 الترتيب\n1. أنت — "+score+"\n2. Player 2 — 2\n3. Player 3 — 1",20));Button n=b("➡ Next Question"),r=b("🔄 Rematch");content.addView(n);content.addView(r);n.setOnClickListener(v->{q++;game();});r.setOnClickListener(v->{q=0;score=0;game();});}
 void chat(){base();content.addView(t("💬 Chat",28));EditText e=new EditText(this);e.setHint("اكتب رسالة...");content.addView(e);Button send=b("Send"),mute=b("🔇 Mute"),back=b("← Back");content.addView(send);content.addView(mute);content.addView(back);send.setOnClickListener(v->{if(e.length()>0){Toast.makeText(this,"تم الإرسال",0).show();e.setText("");}});back.setOnClickListener(v->home());}
 void settings(){base();content.addView(t("⚙ Settings",28));Switch s=new Switch(this);s.setText("Dark Mode");s.setChecked(dark);content.addView(s);content.addView(t("Language: العربية / Français / English",18));Switch so=new Switch(this);so.setText("Sounds");content.addView(so);Button back=b("← Back");content.addView(back);s.setOnCheckedChangeListener((x,c)->{dark=c;settings();});back.setOnClickListener(v->home());}
}