plugins {
    id 'com.android.application'
}

android {
    namespace 'com.guessus.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.guessus.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'

        buildConfigField "String", "SUPABASE_URL", "\"${SUPABASE_URL}\""
        buildConfigField "String", "SUPABASE_KEY", "\"${SUPABASE_KEY}\""
    }

    buildFeatures {
        buildConfig true
    }
}
